# Generated by Django 5.0.1 on 2024-01-12 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDos',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.TextField()),
                ('dev_name', models.CharField(max_length=20)),
                ('pro_type', models.CharField(max_length=20)),
                ('pro_name', models.CharField(max_length=50)),
                ('pro_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('pro_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='todo.todos')),
            ],
        ),
    ]
