# Generated by Django 5.0.1 on 2024-01-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='date',
            field=models.TextField(),
        ),
    ]
